### ISSUE TITLE
GCSの画像へアクセスできない

### ISSUE THREAD

**Issue by yasushisakai** [namaph/instant-idea-sim#6]
@takeseiさん、

`api/v1/visresults/{id}` に記載されているURLの画像がみあたりません。

ex)
https://storage.googleapis.com/instant-sim-viz/4b80b3bf-ba5a-4bdc-82c8-0d5779141f0d_60_graph.png

上のフォルダをみてみてもアップされていないのがわかります。
https://storage.googleapis.com/instant-sim-viz/

**Comment by takesei** [comment]
確認します

**Comment by takesei** [comment]
テストで作ったDBをさくじょしわすれていたのが理由ですね

**Comment by takesei** [comment]
挙動は期待通りみたいです
本来はテストでテストDBを使うべきなのですがそれを略したのが一番の理由ですね
今回は突貫だったので仕方なかったかと思います

問題は解決されたのでCloseします
